---
title: "DMRsegal: End-to-End Example"
author: "DMRsegal Package"
date: "`r Sys.Date()`"
output: BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{DMRsegal: End-to-End Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    warning = TRUE,
    message = TRUE,
    fig.width = 9,
    fig.height = 6,
    dpi = 150
)
```

## Overview

End-to-end DMR discovery with the same dataset and steps as in the benchmark, including DMP selection via `minfi::dmpFinder`, and visualization with `plotDMRs` and `plotDMRWithBeta`.

## Load data and prepare inputs

```{r load}

load(system.file("data/beta.rda", package = "DMRsegal"))
load(system.file("data/pheno.rda", package = "DMRsegal"))
load(system.file("data/array_type.rda", package = "DMRsegal"))
genome <- "hg19"

beta_handler <- DMRsegal::getBetaHandler(beta = beta, array = array_type, genome = genome)
beta_mat <- as.matrix(beta_handler$getBeta())
locs <- beta_handler$getBetaLocs()

# M-values (logit of beta) with small epsilon to avoid log(0)
mvalues <- log2(beta_mat / (1 - beta_mat + 1e-6) + 1e-6)

pheno$group <- pheno$Sample_Group
pheno$casecontrol <- pheno$Sample_Group == "cancer"
```

## Select DMPs with dmpFinder

```{r dmps}
library(minfi)

design <- model.matrix(~group, data = pheno)
colnames(design) <- c("(Intercept)", "cancer_vs_normal")

dmps <- suppressWarnings(dmpFinder(mvalues,
    pheno = pheno$group,
    type = "categorical",
    shrinkVar = TRUE
))

dmps <- dmps[!is.na(dmps$pval), ]
dmps$pval_adj <- p.adjust(dmps$pval, method = "BH")
sig_dmps <- dmps[dmps$pval_adj < 0.05, ]
```

## Find DMRs from seeds

```{r dmrs}
set.seed(42)
dmrs <- DMRsegal::findDMRsFromSeeds(
    beta = beta_handler,
    dmps = sig_dmps,
    pheno = pheno,
    sample_group_col = "group",
    array = array_type,
    genome = genome,
    min_dmps = 2,
    min_adj_dmps = 1,
    min_cpgs = 3,
    max_lookup_dist = 10000,
    max_pval = 0.05,
    pval_mode = "parametric",
    njobs = 1
)
length(dmrs)
```

## Plot multiple DMRs

```{r plot_grid}
if (length(dmrs) > 0) {
    idx <- seq_len(min(4L, length(dmrs)))
    plotDMRs(dmrs, dmr_indices = idx, ncol = 2)
}
```

## Plot a DMR with beta heatmap

```{r plot_beta}
if (length(dmrs) > 0) {
    plotDMRWithBeta(
        dmrs,
        dmr_index = 1,
        beta = beta_handler,
        pheno = pheno,
        sample_group_col = "group",
        max_cpgs = 100
    )
}
```
```{r session_info}
sessionInfo()
```
