# nolint start: object_name_linter, line_length_linter

#' Simulate DMRs with Correlated Effects.
#'
#' Add simulated DMRs to observed control data. Control data will be split into two (artificial) populations.
#' Extends \link[dmrseq]{simDMRs} function, with additional options to control the correlation structure of methylation changes across CpGs within a DMR
#' and across samples.
#'
#' @param bs A BSseq object containing the control data to which DMRs will be added. All loci must have coverage in every sample.
#' @param num.dmrs The number of DMRs to simulate.
#' @param delta.max0 The maximum absolute change in methylation proportion to apply within a DMR. The actual change for each DMR will be randomly varied around this value.
#' @param use.correlated.effects If TRUE, simulates correlated methylation changes across CpGs within a DMR,
#'   creating more realistic regional patterns of differential methylation. If FALSE, simulates independent changes at each CpG site.
#' @param corr.sd Controls the magnitude of the correlated effect across CpGs within a DMR.
#'   Higher values lead to stronger correlation and more coherent DMRs, while lower values result in
#'   weaker correlation and more heterogeneous DMRs.
#' @param corr.length Controls the length scale of the correlation across CpGs within a DMR.
#'   Smaller values lead to more localized correlation (i.e., stronger correlation between
#'   nearby CpGs and weaker correlation between distant CpGs), while larger values lead to
#'   more extended correlation across the DMR.
#' @param sample.sd.frac Controls the magnitude of sample-specific variation relative to the correlated effect.
#'   Higher values lead to more variability between samples, while lower values lead to more consistent effects across samples.
#' @return A named list containing:
#'   \item{gr.dmrs}{A GRanges object with the locations of the simulated DMRs.}
#'   \item{dmr.mncov}{A numeric vector with the mean coverage of each simulated DMR.}
#'   \item{dmr.L}{A numeric vector with the number of CpGs in each simulated DMR.}
#'   \item{bs}{A BSseq object containing the simulated methylation data with the added DMRs.}
#'   \item{delta}{A numeric vector with the maximum methylation change applied to each DMR.}
#' @export
#' @examples
#' \dontrun{
#' # Load example BSseq data
#' data("BS.cancer.ex", package = "bsseqData")
#' # Simulate DMRs with correlated effects
#' sim_data <- simDMRsCorrelated(BS.cancer.ex,
#'     num.dmrs = 100,
#'     delta.max0 = 0.2,
#'     use.correlated.effects = TRUE,
#'     corr.sd = 0.25,
#'     corr.length = 200,
#'     sample.sd.frac = 0.33
#' )
#' }
simDMRsCorrelated <- function(bs,
                              num.dmrs = 3000,
                              delta.max0 = 0.3,
                              use.correlated.effects = TRUE,
                              corr.sd = 0.25,
                              corr.length = 200,
                              sample.sd.frac = 0.33) {
    # check that all loci have coverage in every sample
    zero.cov <- which(rowSums(as.matrix(bsseq::getCoverage(bs, type = "Cov")) == 0) > 0)
    if (length(zero.cov) > 0) {
        stop(
            "Zero coverage found for at least one sample in ", length(zero.cov),
            " loci. Please filter for loci with coverage at least one in ",
            "all samples before passing to 'simDMRs_correlated'"
        )
    }

    sampleSize <- floor(ncol(bs) / 2)
    message(
        "Simulating DMRs for ", sampleSize, " vs ", ncol(bs) - sampleSize,
        " comparison"
    )

    triwt <- function(x, amp = 1, base = 0, width = 1, center = 0,
                      deg = 3, dir = 1) {
        y <- dir * (((width / 2)^deg - abs(x - center)^deg) /
            (width / 2)^deg)^deg * amp + base
        y[abs(x - center) > ceiling(width / 2)] <-
            base[abs(x - center) > ceiling(width / 2)]
        y
    }

    # correlated latent field over CpGs inside a DMR
    # It is generated by sampling from a multivariate normal distribution with an exponential covariance structure,
    # where the correlation between two CpGs decays exponentially with their distance.
    # The 'sigma' parameter controls the overall magnitude of the correlated effect,
    # and the 'length.scale' parameter controls how quickly the correlation decays with distance
    # (smaller values lead to more localized correlation).
    make_correlated_effect <- function(pos, sigma = 0.25, length.scale = 200) {
        n <- length(pos)
        if (n == 1L || sigma <= 0) {
            return(rep(0, n))
        }
        d <- abs(outer(pos, pos, "-"))
        R <- exp(-d / length.scale)
        diag(R) <- diag(R) + 1e-8
        z <- t(chol(R)) %*% rnorm(n)
        as.numeric(sigma * z)
    }

    # apply deterministic smooth effect plus correlated deviation on logit scale
    make_shifted_prob <- function(base.p, diff.hit, pos,
                                  group.field = NULL,
                                  sample.sd = 0,
                                  length.scale = 200,
                                  use.cor = TRUE) {
        eps <- 1e-6
        base.p <- pmin(pmax(base.p, eps), 1 - eps)

        # preserve the original interpretation of Diff.hit as an additive change
        # on the probability scale, then map that change to a logit shift
        target.p <- pmin(pmax(base.p + diff.hit, eps), 1 - eps)
        det.shift <- qlogis(target.p) - qlogis(base.p)

        if (is.null(group.field)) {
            group.field <- rep(0, length(base.p))
        }

        sample.field <- if (use.cor && sample.sd > 0) {
            make_correlated_effect(pos,
                sigma = sample.sd,
                length.scale = length.scale
            )
        } else {
            rep(0, length(base.p))
        }

        plogis(qlogis(base.p) + det.shift + group.field + sample.field)
    }

    meth.mat <- as.matrix(bsseq::getCoverage(bs, type = "M"))
    unmeth.mat <- as.matrix(bsseq::getCoverage(bs, type = "Cov")) - meth.mat
    chr <- as.character(GenomeInfoDb::seqnames(bs))
    pos <- start(bs)

    cluster <- bumphunter::clusterMaker(chr, pos, maxGap = 500)
    Indexes <- split(seq(along = cluster), cluster)
    lns <- lengths(Indexes)
    Indexes <- Indexes[lns >= 5 & lns <= 500]

    # sample regions with intermediate methylation values preferentially
    prop.mat <- rowMeans(meth.mat / (meth.mat + unmeth.mat))
    prop.mat <- unlist(lapply(Indexes, function(x) median(prop.mat[x])))

    dmrs.ind <- sample(seq_along(Indexes),
        num.dmrs,
        replace = FALSE,
        prob = pmax(1 - sqrt(2) * abs(0.5 - prop.mat)^0.5, 0)
    )
    dmrs.ind <- Indexes[dmrs.ind]

    fnc <- function(index) {
        gr.dmr <- GenomicRanges::GRanges(
            seqnames = unique(as.character(GenomeInfoDb::seqnames(bs)[index])),
            IRanges::IRanges(
                start = min(start(bs)[index]),
                end = max(start(bs)[index])
            )
        )
        gr.dmr
    }

    gr.dmrs <- suppressWarnings(Reduce("c", lapply(dmrs.ind, fnc)))

    Diff <- rep(0, length(bs))
    dmr.mncov <- dmr.L <- deltas <- rep(NA, num.dmrs)

    for (u in seq_len(num.dmrs)) {
        up <- 1 - 2 * (rbinom(1, 1, 0.5) == 1)

        # let effect size change randomly
        delta.max <- delta.max0 + (rbeta(1, 2, 2) - 0.5) / 3
        deltas[u] <- delta.max

        idx <- dmrs.ind[[u]]
        dmr.L[u] <- length(idx)

        prop.mat <- meth.mat[idx, ] / (meth.mat[idx, ] + unmeth.mat[idx, ])

        # change direction if baseline mean is near boundary
        if (up == 1) {
            if (mean(prop.mat) > 1 - delta.max) {
                up <- -1
            }
        } else if (up == -1) {
            if (mean(prop.mat) < delta.max) {
                up <- 1
            }
        }

        # simulated mean as a smooth parabola added or subtracted from baseline mean
        last <- max(pos[idx])
        first <- min(pos[idx])
        width <- last - first

        # widen so first and last CpGs do not have zero difference
        last <- last + 0.2 * width
        first <- first - 0.2 * width
        width <- last - first
        mid <- round((last - first) / 2 + first)

        Diff.hit <- round(
            triwt(pos[idx],
                amp = delta.max,
                base = Diff[idx],
                width = width,
                center = mid,
                deg = 4,
                dir = up
            ),
            4
        )

        mn.cov <- by(
            t(meth.mat[idx, ] + unmeth.mat[idx, ]),
            factor(paste0(
                "Condition",
                c(
                    rep(1, sampleSize),
                    rep(2, ncol(bs) - sampleSize)
                )
            )),
            colMeans
        )
        mn.cov <- rowMeans(cbind(mn.cov[[1]], mn.cov[[2]]))
        dmr.mncov[u] <- mean(mn.cov)

        cov <- meth.mat[idx, ] + unmeth.mat[idx, ]
        prop <- meth.mat[idx, ] / cov

        # randomly choose which condition gets the DMR
        grp <- runif(1) < 0.5
        ss <- ifelse(grp, sampleSize, ncol(bs) - sampleSize)

        dmr.pos <- pos[idx]

        # shared correlated field across samples in the affected group
        # gives region-level coherence
        group.field <- if (use.correlated.effects) {
            make_correlated_effect(dmr.pos,
                sigma = corr.sd,
                length.scale = corr.length
            )
        } else {
            rep(0, length(idx))
        }

        # smaller sample-specific field for replicate variation
        sample.sd <- corr.sd * sample.sd.frac

        for (samp in seq_len(ss)) {
            if (grp) {
                new.p <- make_shifted_prob(
                    base.p = prop[, samp],
                    diff.hit = Diff.hit,
                    pos = dmr.pos,
                    group.field = group.field,
                    sample.sd = sample.sd,
                    length.scale = corr.length,
                    use.cor = use.correlated.effects
                )

                meth.mat[idx, samp] <- rbinom(
                    n = length(idx),
                    size = cov[, samp],
                    prob = new.p
                )
                unmeth.mat[idx, samp] <- cov[, samp] - meth.mat[idx, samp]
            } else {
                j <- sampleSize + samp

                new.p <- make_shifted_prob(
                    base.p = prop[, j],
                    diff.hit = Diff.hit,
                    pos = dmr.pos,
                    group.field = group.field,
                    sample.sd = sample.sd,
                    length.scale = corr.length,
                    use.cor = use.correlated.effects
                )

                meth.mat[idx, j] <- rbinom(
                    n = length(idx),
                    size = cov[, j],
                    prob = new.p
                )
                unmeth.mat[idx, j] <- cov[, j] - meth.mat[idx, j]
            }
        }
    }

    sampnames <- paste0(
        "Condition",
        c(
            rep(1, sampleSize),
            rep(2, ncol(bs) - sampleSize)
        ),
        "_Rep",
        c(
            seq_len(sampleSize),
            seq_len(ncol(bs) - sampleSize)
        )
    )

    colnames(meth.mat) <- colnames(unmeth.mat) <- sampnames

    bsNew <- bsseq::BSseq(
        pos = pos, chr = chr, M = meth.mat,
        Cov = (meth.mat + unmeth.mat),
        sampleNames = sampnames
    )

    sim.dat.red <- list(
        gr.dmrs = gr.dmrs,
        dmr.mncov = dmr.mncov,
        dmr.L = dmr.L,
        bs = bsNew,
        delta = deltas
    )

    sim.dat.red
}

# nolint end
