# nolint start: object_name_linter

#' Simulate DMRs while preserving local methylation structure
#'
#' This simulator is inspired by `dmrseq::simDMRs()`, but adds differential
#' signal on the logit methylation scale. The same regional perturbation engine
#' is used across methylation assays by operating on methylated-count and
#' coverage-count representations. For microarray-style beta values, pseudo
#' counts are constructed first, then the same simulation mechanism is applied.
#'
#' @details
#' All inputs are first represented as methylated counts `M` and coverage
#' counts `C`, with beta values estimated as `(M + 0.5) / (C + 1)`. Non-BSseq
#' beta matrices are converted to pseudo-counts with fixed coverage 100. If
#' `covariates` are supplied, their linear effects are removed on the logit
#' methylation scale while preserving each site's mean signal.
#'
#' Candidate regions are contiguous genomic site segments: adjacent sites remain
#' in the same segment when they are on the same chromosome and no more than
#' `max_gap` bp apart. Eligible segments have between `min_sites` and
#' `max_sites` sites. Segment sampling is mildly weighted toward regions whose
#' median methylation is near 0.5, reducing floor and ceiling effects.
#'
#' For each selected DMR, a smooth regional effect profile is evaluated over the
#' selected positions after expanding the segment by `flank_fraction` on both
#' sides. With center `c`, expanded width `W`, and `d = profile_degree`, the
#' site weight is
#' `w_i = (1 - min(|pos_i - c| / (W / 2), 1)^d)^d`. A signed maximum effect is
#' then drawn as `s * delta_max * w_i`, where `s` is chosen as hyper- or
#' hypomethylating and is flipped when needed to avoid the beta-scale boundary.
#'
#' Case-sample probabilities are shifted through the logit scale. For baseline
#' probability `p_i`, intended beta-scale shift `a_i`, and correlated
#' site-level noise `e_i`, the simulated case probability is
#' `plogis(qlogis(p_i) + qlogis(clamp(p_i + a_i)) - qlogis(p_i) + e_i)`.
#' The noise term is generated by smoothing independent normal variates across
#' neighboring sites defined by `neighbor_window`. Its standard deviation is
#' calibrated from a small lookup table so that the induced adjacent-site
#' correlation approaches the larger of `expected_correlation` and the fitted
#' local background correlation, capped at 0.99.
#'
#' Finally, touched methylated counts are regenerated from the shifted
#' probabilities and original coverage. With `resample_counts = TRUE`, counts
#' are drawn as `Binomial(C, p)`; otherwise they are deterministically rounded
#' as `round(C * p)`. Reported truth intervals are based on the intended
#' beta-scale perturbation and `truth_min_delta_beta`, with a fallback to at
#' least `min_sites` strongest sites per DMR.
#'
#' @param beta A BSseq object, a [BetaHandler] object, a beta matrix/data
#'   frame, a path to a beta/tabix file, or a path to an `.rds` file
#'   containing a BSseq object.
#' @param num_dmrs Number of DMRs to spike in.
#' @param delta_max0 Baseline maximum beta-scale effect size near the center of
#'   each DMR.
#' @param groups Optional sample group vector. If `NULL`, the first half of
#'   samples are assigned to `Condition1` and the remaining samples to
#'   `Condition2`.
#' @param case_group Group receiving the differential shift. Defaults to the
#'   second group level.
#' @param samplesheet Optional data frame or path to a tab-delimited sample
#'   sheet with covariates. Row names, a `Sample_ID` column, or an unnamed first
#'   column must identify samples.
#' @param samplesheet_sep Separator for samplesheet files. Default is tab.
#' @param sample_group_col Name of the phenotype column added to the returned
#'   samplesheet. Values are `"case"` for perturbed samples and `"control"` for
#'   all other samples.
#' @param covariates Optional covariate columns in `samplesheet` to regress out
#'   on the logit methylation scale before DMRs are simulated. The per-site
#'   baseline is retained.
#' @param max_gap Maximum gap, in bp, used to form candidate site segments.
#' @param min_sites Minimum number of sites per candidate DMR segment.
#' @param max_sites Maximum number of sites per candidate DMR segment.
#' @param truth_min_delta_beta Minimum intended beta-scale perturbation for a
#'   site to define the reported truth interval. The default, `0`, reports the
#'   full selected segment so simulated flanks are not treated as false
#'   positives during benchmarking.
#' @param delta_jitter Width of the random effect-size jitter around
#'   `delta_max0`.
#' @param expected_correlation Minimum within-DMR expected correlation target.
#'   The per-DMR target is the larger of this value and the estimated local
#'   background correlation, capped to the interval `[0, 0.99]`.
#' @param neighbor_window Number of neighboring sites used to smooth the
#'   index-based correlated random effect inside each DMR. A value of `5`
#'   uses up to two upstream and two downstream neighboring sites.
#' @param profile_degree Degree used by the triweight profile.
#' @param flank_fraction Fraction of the selected segment width added on both
#'   sides before evaluating the triweight profile.
#' @param resample_counts If `TRUE`, methylated counts in touched regions are
#'   redrawn from shifted probabilities and coverage. If `FALSE`, counts are
#'   rounded deterministically.
#' @param array Array platform type. Used only when `beta` is not a BSseq object
#'   or a self-contained [BetaHandler].
#' @param genome Reference genome. Used only when `beta` is not a BSseq object
#'   or a self-contained [BetaHandler].
#' @param sorted_locs Optional genomic locations with `chr`, `start`, and
#'   optionally `end` columns. Used only for non-BSseq inputs.
#' @param beta_row_names_file Optional file with beta row names. Used only for
#'   non-BSseq file inputs.
#' @param chrom_col Chromosome column name for tabix inputs.
#' @param start_col Start column name for tabix inputs.
#' @param njobs Number of parallel jobs for loading non-BSseq inputs.
#' @param verbose Numeric. Logging verbosity level. Default comes from
#'   `getOption("CMEnt.verbose")`.
#'
#' @return A list with simulated output (`simulated`), optional genomic
#'   locations for non-BSseq inputs (`beta_locs`), phenotype data (`pheno`),
#'   and dmrseq-like metadata:
#'   `gr.dmrs`, `dmr.mncov`, `dmr.L`, `delta`, `truth`, `selected_regions`,
#'   `groups`, and `case_group`. For reproducible simulations, call
#'   `set.seed()` before `simulateDMRs()`.
#' @examples
#' beta <- matrix(seq(0.1, 0.9, length.out = 48), nrow = 12)
#' rownames(beta) <- paste0("cg", seq_len(nrow(beta)))
#' colnames(beta) <- paste0("sample", seq_len(ncol(beta)))
#' locs <- data.frame(
#'     chr = "chr1",
#'     start = seq(100, by = 100, length.out = nrow(beta)),
#'     row.names = rownames(beta)
#' )
#' set.seed(1)
#' simulated <- simulateDMRs(
#'     beta, num_dmrs = 1, min_sites = 5, max_sites = 20,
#'     sorted_locs = locs, verbose = 0
#' )
#' @importFrom stats qlogis plogis
#' @export
simulateDMRs <- function(
    beta,
    num_dmrs = 3000L,
    delta_max0 = 0.4,
    groups = NULL,
    case_group = NULL,
    samplesheet = NULL,
    samplesheet_sep = "\t",
    sample_group_col = "Sample_Group",
    covariates = NULL,
    max_gap = 500L,
    min_sites = 5L,
    max_sites = 500L,
    truth_min_delta_beta = 0,
    delta_jitter = 1 / 3,
    expected_correlation = 0.7,
    neighbor_window = 5L,
    profile_degree = 4L,
    flank_fraction = 0.2,
    resample_counts = TRUE,
    array = c("450K", "27K", "EPIC", "EPICv2"),
    genome = c("hg38", "hg19", "hs1", "mm10", "mm39"),
    sorted_locs = NULL,
    beta_row_names_file = NULL,
    chrom_col = "#chrom",
    start_col = "start",
    njobs = getOption("CMEnt.njobs", .defaultNJobs()),
    verbose = getOption("CMEnt.verbose", 1)
) {
    
    old_setting <- options("CMEnt.verbose" = verbose)
    on.exit(options(old_setting), add = TRUE)
    num_dmrs <- as.integer(num_dmrs)
    max_gap <- as.integer(max_gap)
    min_sites <- as.integer(min_sites)
    max_sites <- as.integer(max_sites)
    neighbor_window <- as.integer(neighbor_window)
    profile_degree <- as.integer(profile_degree)

    if (length(num_dmrs) != 1L || is.na(num_dmrs) || num_dmrs < 1L) {
        stop("'num_dmrs' must be a positive integer.")
    }
    if (length(delta_max0) != 1L || !is.finite(delta_max0) || delta_max0 <= 0 || delta_max0 >= 1) {
        stop("'delta_max0' must be a numeric scalar in (0, 1).")
    }
    if (length(max_gap) != 1L || is.na(max_gap) || max_gap < 0L) {
        stop("'max_gap' must be a non-negative integer.")
    }
    if (length(min_sites) != 1L || is.na(min_sites) || min_sites < 1L) {
        stop("'min_sites' must be a positive integer.")
    }
    if (length(max_sites) != 1L || is.na(max_sites) || max_sites < min_sites) {
        stop("'max_sites' must be an integer greater than or equal to 'min_sites'.")
    }
    if (length(truth_min_delta_beta) != 1L || !is.finite(truth_min_delta_beta) || truth_min_delta_beta < 0) {
        stop("'truth_min_delta_beta' must be a non-negative numeric scalar.")
    }
    if (length(delta_jitter) != 1L || !is.finite(delta_jitter) || delta_jitter < 0) {
        stop("'delta_jitter' must be a non-negative numeric scalar.")
    }
    if (length(expected_correlation) != 1L ||
        !is.finite(expected_correlation) ||
        expected_correlation < 0 ||
        expected_correlation > 0.99) {
        stop("'expected_correlation' must be a numeric scalar in [0, 0.99].")
    }
    if (length(neighbor_window) != 1L || is.na(neighbor_window) || neighbor_window < 1L) {
        stop("'neighbor_window' must be a positive integer.")
    }
    if (length(profile_degree) != 1L || is.na(profile_degree) || profile_degree < 1L) {
        stop("'profile_degree' must be a positive integer.")
    }
    if (length(flank_fraction) != 1L || !is.finite(flank_fraction) || flank_fraction < 0) {
        stop("'flank_fraction' must be a non-negative numeric scalar.")
    }
    .log_step("Preparing input...", level = 1)
    input <- .prepareSimulationInput(
        beta = beta,
        array = array,
        genome = genome,
        sorted_locs = sorted_locs,
        beta_row_names_file = beta_row_names_file,
        chrom_col = chrom_col,
        start_col = start_col,
        njobs = njobs
    )

    meth_mat <- input$meth
    cov_mat <- input$cov
    chr <- input$chr
    pos <- input$pos
    end_pos <- input$end
    row_ids <- input$row_ids

    n_samples <- ncol(meth_mat)
    if (n_samples < 2L) {
        stop("Input methylation data must contain at least two samples.")
    }

    groups <- .resolveSimulationGroups(
        groups = groups,
        n_samples = n_samples,
        case_group = case_group
    )
    case_group <- attr(groups, "case_group")
    case_samples <- which(groups == case_group)
    control_samples <- which(groups != case_group)
    if (length(case_samples) == 0L || length(control_samples) == 0L) {
        stop("'case_group' must define at least one case and one non-case sample.")
    }

    sample_names <- input$sample_names
    output_groups <- ifelse(
        seq_len(n_samples) %in% case_samples,
        "case",
        "control"
    )
    output_case_group <- "case"
    if (anyNA(sample_names) || any(!nzchar(sample_names))) {
        stop("Input sample names must be non-empty.")
    }
    if (anyDuplicated(sample_names) > 0L) {
        stop("Input sample names must be unique.")
    }
    covariates <- .normalizeSimulationCovariates(covariates)
    if (!is.null(covariates) && is.null(samplesheet)) {
        stop("'samplesheet' must be provided when 'covariates' are supplied.")
    }
    colnames(meth_mat) <- colnames(cov_mat) <- sample_names
    pheno <- .prepareSimulationPheno(
        samplesheet = samplesheet,
        samplesheet_sep = samplesheet_sep,
        sample_names = sample_names,
        sample_groups = output_groups,
        sample_group_col = sample_group_col
    )

    meth_mat[is.na(meth_mat)] <- 0
    cov_mat[is.na(cov_mat)] <- 0
    meth_mat <- round(meth_mat)
    cov_mat <- round(cov_mat)
    cov_mat[cov_mat < 0] <- 0
    meth_mat[meth_mat < 0] <- 0
    meth_over_cov <- meth_mat > cov_mat
    meth_mat[meth_over_cov] <- cov_mat[meth_over_cov]
    if (!is.null(covariates)) {
        meth_mat <- .residualizeSimulationCounts(
            meth = meth_mat,
            cov = cov_mat,
            pheno = pheno,
            covariates = covariates,
            sample_group_col = sample_group_col
        )
    }

    collapsed_input <- .collapseSimulationDuplicateLoci(
        meth = meth_mat,
        cov = cov_mat,
        chr = chr,
        pos = pos,
        end = end_pos,
        row_ids = row_ids
    )
    collapsed_input <- .orderSimulationLoci(collapsed_input)
    meth_mat <- collapsed_input$meth
    cov_mat <- collapsed_input$cov
    chr <- collapsed_input$chr
    pos <- collapsed_input$pos
    end_pos <- collapsed_input$end
    row_ids <- collapsed_input$row_ids

    .log_step("Identifying candidate genomic segments for DMR simulation...", level = 1)
    segments <- .findContiguousSegments(chr = chr, pos = pos, max_gap = max_gap)
    index_by_segment <- split(seq_along(segments), segments)
    segment_lengths <- lengths(index_by_segment)
    eligible <- which(segment_lengths >= min_sites & segment_lengths <= max_sites)
    if (length(eligible) < num_dmrs) {
        stop(
            "Only ", length(eligible), " eligible candidate genomic segments found, but ",
            num_dmrs, " DMRs were requested. Decrease 'num_dmrs' or relax ",
            "'min_sites'/'max_sites'/'max_gap'."
        )
    }
    # Preferentially select segments with intermediate methylation levels, as these are more likely to yield the intended effect sizes and avoid floor/ceiling effects. 
    # These probabilities are not intended to be exact or to target a specific distribution, but rather to provide a heuristic preference for segments with more dynamic methylation.
    segments_choosing_prob <- vapply(index_by_segment[eligible], function(idx) {
        beta_region <- .convertCountsToBeta(
            meth_mat[idx, , drop = FALSE],
            cov_mat[idx, , drop = FALSE]
        )
        p <- stats::median(rowMeans(beta_region, na.rm = TRUE), na.rm = TRUE)
        if (!is.finite(p)) {
            return(0)
        }
        pmax(1 - sqrt(2) * abs(0.5 - p)^0.5, 0)
    }, numeric(1))
    if (!any(segments_choosing_prob > 0)) {
        segments_choosing_prob <- rep(1, length(eligible))
    }

    dmr_segment_pos <- sample(seq_along(eligible), num_dmrs, replace = FALSE, prob = segments_choosing_prob)
    dmr_segment_ids <- eligible[dmr_segment_pos]
    dmr_indices <- index_by_segment[dmr_segment_ids]

    .log_step("Fitting correlation structure for DMR simulation...", level = 1)
    default_corr_sd <- 0.30
    corr_lookup <- .simulationBuildCorrelationLookup(
        affected_samples = length(case_samples),
        template_length = .simulationTemplateLength(indices = index_by_segment[eligible]),
        template_cov = .simulationTemplateCoverage(cov_mat),
        neighbor_window = neighbor_window
    )
    background_corr_targets <- .simulationFitCorrelationTargets(
        beta = .convertCountsToBeta(meth_mat, cov_mat),
        chr = chr,
        pos = pos,
        group_indices = list(control_samples, case_samples),
        max_gap = max_gap,
        n_targets = num_dmrs
    )
    corr_targets <- pmax(expected_correlation, background_corr_targets, na.rm = TRUE)
    corr_targets[!is.finite(corr_targets)] <- expected_correlation
    corr_targets <- pmin(pmax(corr_targets, 0), 0.99)
    corr_pick_index <- vapply(
        corr_targets,
        .simulationPickCorrelationIndex,
        integer(1),
        lookup = corr_lookup,
        default_corr_sd = default_corr_sd
    )
    corr_sd_used <- corr_lookup$corr_sd[corr_pick_index]
    corr_metric_estimate <- corr_lookup$metric[corr_pick_index]

    truth_rows <- vector("list", num_dmrs)
    truth_gr <- vector("list", num_dmrs)
    selected_gr <- vector("list", num_dmrs)
    deltas <- numeric(num_dmrs)
    dmr_mncov <- numeric(num_dmrs)
    dmr_lengths <- integer(num_dmrs)
    .log_step("Simulating DMRs...", level = 1)
    pb <- utils::txtProgressBar(min = 0, max = num_dmrs, style = 3, width = 50, char = "=", title = "Simulating DMRs")
    for (dmr_i in seq_along(dmr_indices)) {
        idx <- dmr_indices[[dmr_i]]
        eta0 <- .convertCountsToLogits(meth_mat[idx, , drop = FALSE], cov_mat[idx, , drop = FALSE])
        p0 <- plogis(eta0)
        prof <- .simulationEffectProfile(pos[idx], profile_degree, flank_fraction)

        delta_max <- delta_max0 + (stats::rbeta(1L, 2, 2) - 0.5) * delta_jitter
        delta_max <- pmin(pmax(delta_max, 0.01), 0.95)

        direction <- sample(c(-1, 1), 1L)
        reference_beta <- stats::median(p0[, case_samples, drop = FALSE], na.rm = TRUE)
        if (!is.finite(reference_beta)) {
            reference_beta <- stats::median(p0, na.rm = TRUE)
        }
        if (!is.finite(reference_beta)) {
            reference_beta <- 0.5
        }
        if (direction > 0 && reference_beta > 1 - delta_max) {
            direction <- -1
        } else if (direction < 0 && reference_beta < delta_max) {
            direction <- 1
        }
        diff_hit <- direction * delta_max * prof
        current_corr_sd <- corr_sd_used[[dmr_i]]

        p1_case <- matrix(NA_real_, nrow = length(idx), ncol = length(case_samples))
        for (sample_i in seq_along(case_samples)) {
            p1_case[, sample_i] <- .simulationShiftedProbabilities(
                base_prob = p0[, case_samples[[sample_i]]],
                diff_hit = diff_hit,
                corr_sd = current_corr_sd,
                neighbor_window = neighbor_window
            )
        }

        eta1 <- eta0
        eta1[, case_samples] <- stats::qlogis(.clampSimulationBeta(p1_case))

        intended_delta <- rowMeans(p1_case, na.rm = TRUE) -
            rowMeans(p0[, case_samples, drop = FALSE], na.rm = TRUE)
        intended_delta[!is.finite(intended_delta)] <- 0
        truth_local <- which(abs(intended_delta) >= truth_min_delta_beta)
        if (length(truth_local) < min(min_sites, length(idx))) {
            truth_local <- order(abs(intended_delta), decreasing = TRUE)[seq_len(min(min_sites, length(idx)))]
        }
        truth_local <- sort(unique(truth_local))
        truth_idx <- idx[truth_local]

        meth_mat[idx, ] <- .simulationCountsFromEta(
            eta = eta1,
            cov = cov_mat[idx, , drop = FALSE],
            resample_counts = resample_counts
        )

        case_beta <- rowMeans(.convertCountsToBeta(meth_mat[truth_idx, case_samples, drop = FALSE], cov_mat[truth_idx, case_samples, drop = FALSE]), na.rm = TRUE)
        control_beta <- rowMeans(.convertCountsToBeta(meth_mat[truth_idx, control_samples, drop = FALSE], cov_mat[truth_idx, control_samples, drop = FALSE]), na.rm = TRUE)
        observed_delta <- stats::median(case_beta - control_beta, na.rm = TRUE)
        if (!is.finite(observed_delta)) {
            observed_delta <- direction * delta_max
        }

        dmr_mncov[[dmr_i]] <- mean(rowMeans(cov_mat[truth_idx, , drop = FALSE], na.rm = TRUE), na.rm = TRUE)
        dmr_lengths[[dmr_i]] <- length(truth_idx)
        deltas[[dmr_i]] <- observed_delta

        selected_gr[[dmr_i]] <- GenomicRanges::GRanges(
            seqnames = chr[idx[[1L]]],
            ranges = IRanges::IRanges(start = min(pos[idx]), end = max(end_pos[idx]))
        )
        truth_gr[[dmr_i]] <- GenomicRanges::GRanges(
            seqnames = chr[truth_idx[[1L]]],
            ranges = IRanges::IRanges(start = min(pos[truth_idx]), end = max(end_pos[truth_idx]))
        )
        truth_rows[[dmr_i]] <- data.frame(
            seqnames = chr[truth_idx[[1L]]],
            start = min(pos[truth_idx]),
            end = max(end_pos[truth_idx]),
            width = max(end_pos[truth_idx]) - min(pos[truth_idx]) + 1L,
            num_sites = length(truth_idx),
            cov = dmr_mncov[[dmr_i]],
            delta_beta = observed_delta,
            delta_beta_abs = abs(observed_delta),
            intended_delta_beta = stats::median(intended_delta[truth_local], na.rm = TRUE),
            intended_delta_beta_abs = stats::median(abs(intended_delta[truth_local]), na.rm = TRUE),
            direction = ifelse(observed_delta >= 0, "hyper", "hypo"),
            case_group = output_case_group,
            genome = input$genome,
            background_corr_target = background_corr_targets[[dmr_i]],
            expected_correlation = expected_correlation,
            corr_target = corr_targets[[dmr_i]],
            corr_sd_used = current_corr_sd,
            corr_metric_estimate = corr_metric_estimate[[dmr_i]],
            neighbor_window = neighbor_window,
            stringsAsFactors = FALSE
        )
        utils::setTxtProgressBar(pb, dmr_i)
    }

    gr_dmrs <- suppressWarnings(do.call(c, truth_gr))
    selected_regions <- suppressWarnings(do.call(c, selected_gr))
    truth <- do.call(rbind, truth_rows)
    rownames(truth) <- NULL

    GenomicRanges::mcols(gr_dmrs)$cov <- dmr_mncov
    GenomicRanges::mcols(gr_dmrs)$num_sites <- dmr_lengths
    GenomicRanges::mcols(gr_dmrs)$delta_beta <- deltas
    GenomicRanges::mcols(gr_dmrs)$delta_beta_abs <- abs(deltas)
    GenomicRanges::mcols(gr_dmrs)$case_group <- output_case_group
    GenomicRanges::mcols(gr_dmrs)$genome <- input$genome
    GenomicRanges::mcols(gr_dmrs)$background_corr_target <- background_corr_targets
    GenomicRanges::mcols(gr_dmrs)$expected_correlation <- expected_correlation
    GenomicRanges::mcols(gr_dmrs)$corr_target <- corr_targets
    GenomicRanges::mcols(gr_dmrs)$corr_sd_used <- corr_sd_used
    GenomicRanges::mcols(gr_dmrs)$corr_metric_estimate <- corr_metric_estimate
    GenomicRanges::mcols(gr_dmrs)$neighbor_window <- neighbor_window

    colnames(meth_mat) <- colnames(cov_mat) <- sample_names
    .log_step("Building output object...", level = 1)
    output <- .buildSimulationOutputObject(
        input = input,
        meth = meth_mat,
        cov = cov_mat,
        chr = chr,
        pos = pos,
        end_pos = end_pos,
        row_ids = row_ids,
        sample_names = sample_names,
        pheno = pheno
    )

    result <- list(
        gr.dmrs = gr_dmrs,
        dmr.mncov = dmr_mncov,
        dmr.L = dmr_lengths,
        simulated = output$simulated,
        pheno = pheno,
        assay = input$assay,
        delta = deltas,
        truth = truth,
        selected_regions = selected_regions,
        groups = stats::setNames(output_groups, sample_names),
        case_group = output_case_group,
        genome = input$genome,
        background_corr_target = background_corr_targets,
        expected_correlation = expected_correlation,
        corr_target = corr_targets,
        corr_sd_used = corr_sd_used,
        corr_metric_estimate = corr_metric_estimate,
        neighbor_window = neighbor_window,
        covariates = covariates,
        input_groups = stats::setNames(as.character(groups), sample_names),
        input_case_group = case_group,
        duplicate_loci_collapsed = collapsed_input$n_collapsed
    )

    if (!is.null(output$beta_locs)) {
        result$beta_locs <- output$beta_locs
    }

    .log_info("Simulation complete!", level = 1)
    result
}

.prepareSimulationInput <- function(beta,
                                    array,
                                    genome,
                                    sorted_locs,
                                    beta_row_names_file,
                                    chrom_col,
                                    start_col,
                                    njobs) {
    if (
        is.character(beta) &&
            length(beta) == 1L &&
            file.exists(beta) &&
            tolower(tools::file_ext(beta)) == "rds"
    ) {
        beta_rds <- readRDS(beta)
        if (inherits(beta_rds, "BSseq")) {
            beta <- beta_rds
        }
    }

    if (inherits(beta, "BSseq")) {
        bs <- sort(beta)
        meth_mat <- as.matrix(bsseq::getCoverage(bs, type = "M"))
        cov_mat <- as.matrix(bsseq::getCoverage(bs, type = "Cov"))
        gr <- GenomicRanges::granges(bs)
        input_genome <- unique(as.character(GenomeInfoDb::genome(gr)))
        input_genome <- input_genome[!is.na(input_genome) & nzchar(input_genome)]
        if (length(input_genome) != 1L) {
            input_genome <- NA_character_
        }
        chr <- as.character(GenomeInfoDb::seqnames(gr))
        pos <- GenomicRanges::start(gr)
        end_pos <- GenomicRanges::end(gr)
        row_ids <- paste0(chr, ":", pos)
        sample_names <- colnames(bs)
        if (is.null(sample_names)) {
            sample_names <- paste0("sample_", seq_len(ncol(meth_mat)))
        }
        return(list(
            assay = "BSseq",
            source = bs,
            seqinfo = GenomeInfoDb::seqinfo(bs),
            sample_names = sample_names,
            row_ids = row_ids,
            chr = chr,
            pos = pos,
            end = end_pos,
            genome = input_genome,
            meth = meth_mat,
            cov = cov_mat
        ))
    }
    if (!is.null(sorted_locs)) {
        if (!all(c("chr", "start") %in% colnames(sorted_locs))) {
            stop("When provided, 'sorted_locs' must contain 'chr' and 'start' columns.")
        }
        if (!is.character(sorted_locs$chr) || !is.numeric(sorted_locs$start)) {
            stop("'chr' column in 'sorted_locs' must be character and 'start' column must be numeric.")
        }
        sorted_locs <- sorted_locs[order(sorted_locs$chr, sorted_locs$start), , drop = FALSE]
    }
    beta_handler <- getBetaHandler(
        beta = beta,
        array = array,
        genome = genome,
        beta_row_names_file = beta_row_names_file,
        sorted_locs = sorted_locs,
        chrom_col = chrom_col,
        start_col = start_col,
        njobs = njobs
    )

    beta_mat <- as.matrix(beta_handler$getBeta())
    beta_locs <- as.data.frame(beta_handler$getBetaLocs())
    if (!all(c("chr", "start") %in% colnames(beta_locs))) {
        stop("Non-BSseq simulation requires genomic locations with 'chr' and 'start' columns.")
    }
    if (!("end" %in% colnames(beta_locs))) {
        beta_locs$end <- beta_locs$start
    }

    if (is.null(rownames(beta_locs)) || any(!nzchar(rownames(beta_locs)))) {
        beta_locs_ids <- paste0(as.character(beta_locs$chr), ":", as.integer(beta_locs$start))
        rownames(beta_locs) <- make.unique(beta_locs_ids)
    }

    if (is.null(rownames(beta_mat)) || any(!nzchar(rownames(beta_mat)))) {
        if (nrow(beta_mat) != nrow(beta_locs)) {
            stop("Unable to align non-BSseq beta values with genomic locations.")
        }
        rownames(beta_mat) <- rownames(beta_locs)
    }

    common_ids <- rownames(beta_locs)[rownames(beta_locs) %in% rownames(beta_mat)]
    if (length(common_ids) == 0L) {
        stop("No overlapping row identifiers between beta values and genomic locations.")
    }
    beta_locs <- beta_locs[common_ids, , drop = FALSE]
    beta_mat <- beta_mat[common_ids, , drop = FALSE]

    suppressWarnings(storage.mode(beta_mat) <- "double")
    invalid_mask <- !is.finite(beta_mat)
    beta_mat[invalid_mask] <- 0
    beta_mat <- .clampSimulationBeta(beta_mat)

    cov_mat <- matrix(
        100L,
        nrow = nrow(beta_mat),
        ncol = ncol(beta_mat),
        dimnames = dimnames(beta_mat)
    )
    cov_mat[invalid_mask] <- 0
    meth_mat <- round(beta_mat * cov_mat)
    meth_mat[invalid_mask] <- 0

    sample_names <- colnames(beta_mat)
    if (is.null(sample_names)) {
        sample_names <- paste0("sample_", seq_len(ncol(beta_mat)))
    }

    list(
        assay = "microarray",
        source = beta_handler,
        sample_names = sample_names,
        row_ids = rownames(beta_mat),
        chr = as.character(beta_locs$chr),
        pos = as.integer(beta_locs$start),
        end = as.integer(beta_locs$end),
        genome = beta_handler$genome,
        meth = meth_mat,
        cov = cov_mat,
        beta_locs = beta_locs
    )
}

.buildSimulationOutputObject <- function(input,
                                         meth,
                                         cov,
                                         chr,
                                         pos,
                                         end_pos,
                                         row_ids,
                                         sample_names,
                                         pheno) {
    if (identical(input$assay, "BSseq")) {
        bs_new <- bsseq::BSseq(
            chr = chr,
            pos = pos,
            M = meth,
            Cov = cov,
            sampleNames = sample_names
        )
        if (!is.null(input$seqinfo)) {
            GenomeInfoDb::seqinfo(bs_new) <- input$seqinfo
        }
        SummarizedExperiment::colData(bs_new) <- S4Vectors::DataFrame(
            pheno,
            row.names = sample_names
        )
        return(list(
            simulated = bs_new,
            beta_locs = NULL
        ))
    }

    beta_new <- .convertCountsToBeta(meth = meth, cov = cov)
    rownames(beta_new) <- row_ids
    colnames(beta_new) <- sample_names
    beta_locs <- data.frame(
        chr = chr,
        start = as.integer(pos),
        end = as.integer(end_pos),
        row.names = row_ids,
        stringsAsFactors = FALSE
    )

    list(
        simulated = beta_new,
        beta_locs = beta_locs
    )
}

.prepareSimulationPheno <- function(samplesheet,
                                    samplesheet_sep,
                                    sample_names,
                                    sample_groups,
                                    sample_group_col) {
    if (length(sample_group_col) != 1L || is.na(sample_group_col) || !nzchar(sample_group_col)) {
        stop("'sample_group_col' must be a non-empty character scalar.")
    }

    if (is.null(samplesheet)) {
        pheno <- stats::setNames(
            data.frame(sample_groups, stringsAsFactors = FALSE),
            sample_group_col
        )
        rownames(pheno) <- sample_names
        return(pheno)
    }

    if (is.character(samplesheet) && length(samplesheet) == 1L) {
        pheno <- utils::read.table(
            samplesheet,
            header = TRUE,
            stringsAsFactors = FALSE,
            sep = samplesheet_sep,
            check.names = FALSE
        )
        if (ncol(pheno) > 0L && colnames(pheno)[[1L]] == "") {
            rownames(pheno) <- as.character(pheno[[1L]])
            pheno <- pheno[, -1L, drop = FALSE]
        }
    } else if (is.data.frame(samplesheet)) {
        pheno <- as.data.frame(samplesheet)
    } else {
        stop("'samplesheet' must be NULL, a file path, or a data frame.")
    }

    colnames(pheno) <- trimws(colnames(pheno))
    if (.simulationHasDefaultRowNames(pheno) && "Sample_ID" %in% colnames(pheno)) {
        rownames(pheno) <- as.character(pheno$Sample_ID)
    }
    if (.simulationHasDefaultRowNames(pheno)) {
        stop("'samplesheet' must have sample row names or a 'Sample_ID' column.")
    }
    if (anyNA(rownames(pheno)) || any(!nzchar(rownames(pheno)))) {
        stop("'samplesheet' row names must be non-empty sample names.")
    }
    if (anyDuplicated(rownames(pheno)) > 0L) {
        stop("'samplesheet' sample names must be unique.")
    }

    missing_samples <- setdiff(sample_names, rownames(pheno))
    if (length(missing_samples) > 0L) {
        stop(
            "The following input samples are missing from samplesheet: ",
            paste(head(missing_samples, 10), collapse = ", "),
            if (length(missing_samples) > 10L) " ..." else ""
        )
    }

    pheno <- pheno[sample_names, , drop = FALSE]
    pheno[[sample_group_col]] <- sample_groups
    pheno
}

.simulationHasDefaultRowNames <- function(x) {
    identical(rownames(x), as.character(seq_len(nrow(x))))
}

.normalizeSimulationCovariates <- function(covariates) {
    if (is.null(covariates)) {
        return(NULL)
    }
    if (length(covariates) == 1L && is.character(covariates)) {
        covariates <- unlist(strsplit(covariates, ","))
    }
    covariates <- trimws(as.character(covariates))
    covariates <- covariates[nzchar(covariates)]
    if (length(covariates) == 0L) {
        return(NULL)
    }
    unique(covariates)
}

.residualizeSimulationCounts <- function(meth,
                                         cov,
                                         pheno,
                                         covariates,
                                         sample_group_col) {
    if (is.null(covariates)) {
        return(meth)
    }
    if (is.null(pheno)) {
        stop("'samplesheet' must be provided when 'covariates' are supplied.")
    }
    if (sample_group_col %in% covariates) {
        stop("'covariates' must not include 'sample_group_col'.")
    }
    covariate_model <- .prepareCovariateModel(pheno = pheno, covariates = covariates)
    if (is.null(covariate_model) || isTRUE(covariate_model$is_singular)) {
        return(meth)
    }
    non_intercept <- colnames(covariate_model$covariate_matrix) != "(Intercept)"
    if (!any(non_intercept)) {
        return(meth)
    }
    if (ncol(meth) != nrow(covariate_model$covariate_matrix)) {
        stop("Input samples and covariate rows must have the same length.")
    }

    signal <- .convertCountsToLogits(meth = meth, cov = cov)
    signal[!is.finite(signal)] <- 0
    coef <- t(covariate_model$pseudo_solution %*% t(signal))
    fitted_covariates <- coef[, non_intercept, drop = FALSE] %*%
        t(covariate_model$covariate_matrix[, non_intercept, drop = FALSE])
    residualized_signal <- signal - fitted_covariates
    residualized_signal <- residualized_signal +
        rowMeans(signal, na.rm = TRUE) -
        rowMeans(residualized_signal, na.rm = TRUE)
    residualized_prob <- plogis(residualized_signal)
    residualized_meth <- round(residualized_prob * cov)
    residualized_meth[cov <= 0] <- 0
    residualized_meth[residualized_meth < 0] <- 0
    over_cov <- residualized_meth > cov
    residualized_meth[over_cov] <- cov[over_cov]
    dimnames(residualized_meth) <- dimnames(meth)
    residualized_meth
}

.collapseSimulationDuplicateLoci <- function(meth, cov, chr, pos, end = NULL, row_ids = NULL) {
    key <- paste(chr, pos, sep = "\t")
    duplicate_mask <- duplicated(key)
    if (is.null(end)) {
        end <- pos
    }
    if (is.null(row_ids)) {
        row_ids <- paste0(chr, ":", pos)
    }

    if (!any(duplicate_mask)) {
        return(list(
            meth = meth,
            cov = cov,
            chr = chr,
            pos = pos,
            end = end,
            row_ids = row_ids,
            n_collapsed = 0L
        ))
    }

    first_idx <- match(unique(key), key)
    meth_collapsed <- rowsum(meth, group = key, reorder = FALSE)
    cov_collapsed <- rowsum(cov, group = key, reorder = FALSE)
    colnames(meth_collapsed) <- colnames(meth)
    colnames(cov_collapsed) <- colnames(cov)

    row_ids_collapsed <- as.character(row_ids[first_idx])
    if (anyDuplicated(row_ids_collapsed) > 0L) {
        row_ids_collapsed <- make.unique(row_ids_collapsed)
    }

    list(
        meth = as.matrix(meth_collapsed),
        cov = as.matrix(cov_collapsed),
        chr = chr[first_idx],
        pos = pos[first_idx],
        end = end[first_idx],
        row_ids = row_ids_collapsed,
        n_collapsed = as.integer(sum(duplicate_mask))
    )
}

.orderSimulationLoci <- function(x) {
    ord <- order(x$chr, x$pos, x$end, na.last = TRUE)
    if (identical(ord, seq_along(ord))) {
        return(x)
    }
    x$meth <- x$meth[ord, , drop = FALSE]
    x$cov <- x$cov[ord, , drop = FALSE]
    x$chr <- x$chr[ord]
    x$pos <- x$pos[ord]
    x$end <- x$end[ord]
    x$row_ids <- x$row_ids[ord]
    x
}

.resolveSimulationGroups <- function(groups, n_samples, case_group = NULL) {
    if (is.null(groups)) {
        n_control <- floor(n_samples / 2)
        groups <- c(
            rep("Condition1", n_control),
            rep("Condition2", n_samples - n_control)
        )
    }
    groups <- as.character(groups)
    if (length(groups) != n_samples) {
        stop("'groups' must have length equal to the number of samples.")
    }
    if (anyNA(groups) || any(!nzchar(groups))) {
        stop("'groups' must not contain missing or empty values.")
    }
    group_levels <- unique(groups)
    if (length(group_levels) < 2L) {
        stop("'groups' must contain at least two groups.")
    }
    if (is.null(case_group)) {
        case_group <- group_levels[[2L]]
    }
    case_group <- as.character(case_group)[[1L]]
    if (!case_group %in% group_levels) {
        stop("'case_group' must be one of: ", paste(group_levels, collapse = ", "))
    }
    attr(groups, "case_group") <- case_group
    groups
}

.findContiguousSegments <- function(chr, pos, max_gap) {
    if (length(chr) != length(pos)) {
        stop("'chr' and 'pos' must have the same length.")
    }
    if (length(chr) == 0L) {
        return(integer(0))
    }
    pos_diff <- diff(pos)
    starts <- c(TRUE, chr[-1L] != chr[-length(chr)] | pos_diff < 0L | pos_diff > max_gap)
    cumsum(starts)
}

.simulationEffectProfile <- function(pos, degree, flank_fraction) {
    first <- min(pos)
    last <- max(pos)
    width <- max(last - first, 1)
    first <- first - flank_fraction * width
    last <- last + flank_fraction * width
    width <- max(last - first, 1)
    center <- first + width / 2
    scaled <- abs(pos - center) / (width / 2)
    out <- (1 - pmin(scaled, 1)^degree)^degree
    out[!is.finite(out)] <- 0
    pmax(out, 0)
}

.createCorrelatedEffectPrior <- function(n_sites,
                                         sigma = 0.25,
                                         neighbor_weight = 0.7,
                                         neighbor_window = 5L) {
    if (n_sites <= 1L || !is.finite(sigma) || sigma <= 0) {
        return(rep(0, n_sites))
    }
    if (!is.finite(neighbor_weight)) {
        neighbor_weight <- 0.7
    }
    neighbor_weight <- pmax(neighbor_weight, 0)
    neighbor_window <- as.integer(neighbor_window)
    if (length(neighbor_window) != 1L || is.na(neighbor_window) || neighbor_window < 1L) {
        neighbor_window <- 5L
    }
    neighbor_radius <- min(n_sites - 1L, floor(neighbor_window / 2L))

    site_noise <- stats::rnorm(n_sites)
    latent <- site_noise
    latent_var <- rep(1, n_sites)

    if (neighbor_radius > 0L && neighbor_weight > 0) {
        for (offset in seq_len(neighbor_radius)) {
            weight <- neighbor_weight^offset
            left_idx <- seq.int(offset + 1L, n_sites)
            right_idx <- seq_len(n_sites - offset)
            latent[left_idx] <- latent[left_idx] + weight * site_noise[right_idx]
            latent[right_idx] <- latent[right_idx] + weight * site_noise[left_idx]
            latent_var[left_idx] <- latent_var[left_idx] + weight^2
            latent_var[right_idx] <- latent_var[right_idx] + weight^2
        }
    }
    latent <- latent / sqrt(latent_var)
    as.numeric(sigma * latent)
}

.simulationShiftedProbabilities <- function(base_prob,
                                            diff_hit,
                                            corr_sd = 0,
                                            neighbor_window = 5L) {
    base_prob <- .clampSimulationBeta(base_prob)
    target_prob <- .clampSimulationBeta(base_prob + diff_hit)
    det_shift <- stats::qlogis(target_prob) - stats::qlogis(base_prob)

    correlated_effect <- if (corr_sd > 0) {
        .createCorrelatedEffectPrior(
            n_sites = length(base_prob),
            sigma = corr_sd,
            neighbor_window = neighbor_window
        )
    } else {
        rep(0, length(base_prob))
    }

    plogis(stats::qlogis(base_prob) + det_shift + correlated_effect)
}

.simulationComputePairCorrelations <- function(x, y) {
    if (length(x) == 0L || ncol(x) < 2L || !all(dim(x) == dim(y))) {
        return(numeric(0))
    }
    x_centered <- x - rowMeans(x)
    y_centered <- y - rowMeans(y)
    denom <- sqrt(rowSums(x_centered^2) * rowSums(y_centered^2))
    cors <- rowSums(x_centered * y_centered) / denom
    cors[is.finite(cors)]
}

.simulationBackgroundFitCorrelations <- function(beta, chr, pos, group_indices, max_gap) {
    ord <- order(chr, pos)
    beta_ord <- beta[ord, , drop = FALSE]
    chr_ord <- chr[ord]
    pos_ord <- pos[ord]
    segment_ord <- .findContiguousSegments(chr_ord, pos_ord, max_gap = max_gap)
    pair_end <- which(
        chr_ord[-1L] == chr_ord[-length(chr_ord)] &
            segment_ord[-1L] == segment_ord[-length(segment_ord)]
    ) + 1L
    pair_start <- pair_end - 1L
    if (length(pair_start) == 0L) {
        return(numeric(0))
    }

    pooled <- unlist(lapply(group_indices, function(idx) {
        if (length(idx) < 2L) {
            return(numeric(0))
        }
        m_values <- .transformBeta(
            beta_ord[, idx, drop = FALSE],
            pheno = data.frame(sample = seq_len(length(idx)))
        )
        pair_corr <- .simulationComputePairCorrelations(
            x = m_values[pair_start, , drop = FALSE],
            y = m_values[pair_end, , drop = FALSE]
        )
        pair_corr[pair_corr > 0]
    }))
    pooled[is.finite(pooled)]
}

.simulationFitCorrelationTargets <- function(beta,
                                             chr,
                                             pos,
                                             group_indices,
                                             max_gap,
                                             n_targets,
                                             corr_rate = 1) {
    pos_corr <- .simulationBackgroundFitCorrelations(
        beta = beta,
        chr = chr,
        pos = pos,
        group_indices = group_indices,
        max_gap = max_gap
    )
    if (length(pos_corr) < 20L) {
        return(rep(NA_real_, n_targets))
    }

    corr_mean <- mean(pos_corr)
    corr_var <- stats::var(pos_corr)
    if (!is.finite(corr_mean) || !is.finite(corr_var) || corr_mean <= 0 || corr_var <= 1e-8) {
        return(rep(NA_real_, n_targets))
    }

    shape <- corr_mean^2 / corr_var
    rate <- corr_mean / corr_var
    if (!is.finite(shape) || !is.finite(rate) || shape <= 0 || rate <= 0) {
        return(rep(NA_real_, n_targets))
    }

    pmin(
        pmax(
            stats::rgamma(n = n_targets, shape = shape, rate = rate) * corr_rate,
            0
        ),
        0.99
    )
}

.simulationCorrelationMetric <- function(corr_sd,
                                         affected_samples,
                                         template_length,
                                         template_cov,
                                         neighbor_window = 5L,
                                         pilot_reps = 6L) {
    if (affected_samples < 2L || template_length < 2L || corr_sd <= 0) {
        return(0)
    }

    rep_metrics <- numeric(pilot_reps)
    base_prob <- matrix(0.5, nrow = template_length, ncol = affected_samples)
    diff_hit <- rep(0, template_length)

    for (rep_i in seq_len(pilot_reps)) {
        beta_sim <- matrix(NA_real_, nrow = template_length, ncol = affected_samples)
        for (sample_i in seq_len(affected_samples)) {
            new_prob <- .simulationShiftedProbabilities(
                base_prob = base_prob[, sample_i],
                diff_hit = diff_hit,
                corr_sd = corr_sd,
                neighbor_window = neighbor_window
            )
            beta_sim[, sample_i] <- stats::rbinom(
                n = template_length,
                size = template_cov,
                prob = new_prob
            ) / template_cov
        }
        m_values <- .transformBeta(
            beta_sim,
            pheno = data.frame(sample = seq_len(affected_samples))
        )
        pair_corr <- .simulationComputePairCorrelations(
            x = m_values[-nrow(m_values), , drop = FALSE],
            y = m_values[-1L, , drop = FALSE]
        )
        pair_corr <- pair_corr[pair_corr > 0]
        rep_metrics[rep_i] <- if (length(pair_corr) == 0L) 0 else mean(pair_corr)
    }

    mean(rep_metrics)
}

.simulationBuildCorrelationLookup <- function(affected_samples,
                                              template_length,
                                              template_cov,
                                              neighbor_window = 5L,
                                              corr_sd_grid = seq(0.1, 3.0, by = 0.1)) {
    if (affected_samples < 2L || template_length < 2L) {
        return(data.frame(corr_sd = 0.30, metric = 0))
    }

    withr::with_seed(1, {
        data.frame(
            corr_sd = corr_sd_grid,
            metric = vapply(
                corr_sd_grid,
                .simulationCorrelationMetric,
                numeric(1),
                affected_samples = affected_samples,
                template_length = template_length,
                template_cov = template_cov,
                neighbor_window = neighbor_window
            )
        )
    })
}

.simulationPickCorrelationIndex <- function(target, lookup, default_corr_sd = 0.30) {
    if (is.null(lookup) || nrow(lookup) == 0L) {
        return(1L)
    }
    valid_sd <- is.finite(lookup$corr_sd)
    valid_metric <- valid_sd & is.finite(lookup$metric)
    if (!any(valid_metric)) {
        if (any(valid_sd)) {
            return(which(valid_sd)[which.min(abs(lookup$corr_sd[valid_sd] - default_corr_sd))])
        }
        return(1L)
    }
    valid_idx <- which(valid_metric)
    if (!is.finite(target)) {
        return(valid_idx[which.min(abs(lookup$corr_sd[valid_idx] - default_corr_sd))])
    }
    valid_idx[which.min(abs(lookup$metric[valid_idx] - target))]
}

.simulationPickCorrelationSd <- function(target, lookup, default_corr_sd = 0.30) {
    if (is.null(lookup) || nrow(lookup) == 0L) {
        return(default_corr_sd)
    }
    lookup$corr_sd[[.simulationPickCorrelationIndex(
        target = target,
        lookup = lookup,
        default_corr_sd = default_corr_sd
    )]]
}

.simulationTemplateLength <- function(indices, min_len = 5L) {
    segment_lengths <- lengths(indices)
    max(min_len, as.integer(round(stats::median(segment_lengths))))
}

.simulationTemplateCoverage <- function(cov) {
    template_cov <- stats::median(cov[cov > 0], na.rm = TRUE)
    if (!is.finite(template_cov) || template_cov < 1) {
        template_cov <- 100
    }
    as.integer(round(template_cov))
}

.convertCountsToBeta <- function(meth, cov) {
    beta <- (meth + 0.5) / (cov + 1)
    beta[cov <= 0] <- NA_real_
    beta
}

.convertCountsToLogits <- function(meth, cov) {
    stats::qlogis(.clampSimulationBeta(.convertCountsToBeta(meth, cov)))
}

.clampSimulationBeta <- function(x) {
    x_dim <- dim(x)
    x_dimnames <- dimnames(x)
    out <- pmin(pmax(x, 1e-6), 1 - 1e-6)
    if (!is.null(x_dim)) {
        dim(out) <- x_dim
        dimnames(out) <- x_dimnames
    }
    out
}

.simulationCountsFromEta <- function(eta, cov, resample_counts) {
    prob <- plogis(eta)
    prob[!is.finite(prob)] <- 0.5
    cov <- round(cov)
    cov[cov < 0] <- 0
    if (isTRUE(resample_counts)) {
        out <- matrix(
            stats::rbinom(length(cov), size = c(cov), prob = c(prob)),
            nrow = nrow(cov),
            ncol = ncol(cov)
        )
    } else {
        out <- round(cov * prob)
    }
    out[out < 0] <- 0
    out_over_cov <- out > cov
    out[out_over_cov] <- cov[out_over_cov]
    out
}

# nolint end: object_name_linter
