on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-latest,   r: "release" }
          - { os: ubuntu-latest,  r: "release" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v3.3.0
        with:
          channels: conda-forge,bioconda,defaults
          channel-priority: strict
          environment-file: envs/ci_env.yaml
          auto-activate: true

      - name: Debug conda
        run: |
          conda info --envs
          conda env export -n ci_env

      - name: Install macOS system dependencies
        if: matrix.config.os == 'macos-latest'
        run: |
          brew install imagemagick@6
          brew install libgit2

      - name: Install Linux system dependencies
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagick++-dev libgit2-dev

      - name: Setup r-ci
        id: r-ci
        run: |
          curl -OLs https://eddelbuettel.github.io/r-ci/run.sh
          chmod 0755 run.sh
          export BACKEND=BSPM
          ./run.sh bootstrap
        shell: bash

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          extra-packages: |
            any::rcmdcheck
            any::IlluminaHumanMethylation450kanno.ilmn12.hg19
            any::IlluminaHumanMethylationEPICanno.ilm10b4.hg19
            any::knitr
            any::rmarkdown
            any::BiocStyle
            any::DMRcate
            any::bumphunter
            any::doParallel
            any::magick
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: always
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'